# Generated by Django 4.1.7 on 2024-05-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item", name="item_name", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
